### PR TITLE
Added Midnight Theme

### PR DESCRIPTION
**Pull request by dmberrycom**
Addition of midnight theme and simplified theme handling.

### CODE REVIEW

**Comment by kolinger** [comment]
Wow, that's quite a bit of work you made! I think apart of few details this will be good addition. Good work!

Quite confusing merge since there are changes you reverted back? Like "Experimental Connection/Disconnection UI" is not present anymore? Doesn't matter. I can still work with this just makes my work harder.

I see issue with enlargement of Session name input - this now breaks navigation when TC66C is selected with BLE address (or with long COM port name).
image
I would shrink Session name back to smaller size so this won't happen. What do you think?

Another issue is breakage of icons (this is view when browser window is reduced):
image
Icons no longer work since bootstrap uses relative path "../fonts/x" in CSS and this will not work if bootstrap.css is placed under another directory. Easiest solution is to adjust fonts path in each boostrap.css to make it work with new folder structure. I can do it by myself or you can fix it if you want.

Minor issue with midnight, hover doesn't have good contrast I think:
image
Dark color would be better choice?

**Comment by dmberrycom** [comment]
Apologies for the confusion, I'm still learning my way through git so sometimes I make mistakes.

The experimental connect/disconnect UI accidently got pushed. I was just experimenting about wrapping the connection/disconnection notification into the "Connect/Disconnect" button. Firstly to save some real estate and also to give a more visual representation of if the device was connected or not.

image

**Session Field Length** 
This one I think I will need to look at again on my side, I had expanded as the text was getting cut off. On looking at it again it actually seems to be something strange with two dates being shown on my side.

image
 

**Theme Fonts** 
I've updated the files to support the new location (hopefully)

**Midnight Theme - Contrast Issue** 
I've aligned this with the hover behaviour of the other elements for consistency.
image

**Comment by kolinger** [comment]
**Session Field Length**
Yes, if session name is too long then it won't fit into input but that's not a issue. Whole name will be used you just don't see whole name. But you can move cursor in input and then you see rest as usual with inputs.

If bigger session name input is wanted then we wound need to change layout. There is just no room to fit navigation and connection panel together with long session name input. Something would need to move somewhere else and I can't think of any elegant solutions so far. Maybe some dropdown panel for connection? Not sure. Too much work for not much benefit I think.

Since session name was short until now then I don't think it will hurt if it will continue to be short.

**Theme Fonts**
Now works with all themes 👍.

**Midnight Theme - Contrast Issue**
Much better 👍.

**Comment by dmberrycom** [comment]
Yes I agree, I've reverted this back to the original value (150)

**Comment by kolinger** [comment]
Thank you for contribution! 👍

**Pull request merged**
